"use client";
import React, { useState } from "react";
import {
  APIProvider,
  Map,
  AdvancedMarker,
  MapCameraChangedEvent,
  MapCameraProps,
  Pin,
  InfoWindow,
} from "@vis.gl/react-google-maps";
// import markerIcon from '../assets/markericon.png'
// import { useEffect, useState } from 'react'; // For use if generating the coordinates dynamically

const centerPosition = { lat: 40.635603, lng: -111.904922 };
// 10.5 is the Salt Lake Valley, 15 is neighborhood or freeway exit
const defaultZoom = 15;

// use https://www.gps-coordinates.net/ to convert addresses to coordinates for input below
const propertyCoordinates = [
  { lat: 40.76826, lng: -111.9011 }, // Chick-fil-A Delta Center
  { lat: 40.76869, lng: -111.88867 }, // Chick-fil-A City Creek
  { lat: 40.725079, lng: -111.85643 }, // Chick-fil-A Sugarhouse
  { lat: 40.70097, lng: -112.02549 }, // Chick-fil-A West Valley
  { lat: 40.65067, lng: -111.93951 }, // Chick-fil-A Taylorsville
  { lat: 40.65855, lng: -111.888201 }, // Chick-fil-A Murray North
  { lat: 40.636142, lng: -111.889318 }, // Chick-fil-A Murray South
  { lat: 40.623162, lng: -111.862369 }, // Chick-fil-A Fort Union, Midvale
  { lat: 40.624043, lng: -111.984369 }, // Chick-fil-A West Jordan
  { lat: 40.567447, lng: -111.890801 }, // Chick-fil-A Sandy
  { lat: 40.5424775, lng: -111.9836537 }, // Chick-fil-A The District, South Jordan
  { lat: 40.524214, lng: -111.879364 }, // Chick-fil-A Draper
  { lat: 40.524214, lng: -111.936244 }, // Chick-fil-A Riverton
];

const GoogleMap: React.FC<{ apiKey: string; mapId: string }> = ({
  apiKey,
  mapId,
}) => {
  // const mapsURL = 'https://maps.googleapis.com/maps/api/geocode/json?&address'; // for use if we need dynamic address-to-coordinate conversion
  // const [propertyCoordinates, setPropertyCoordinates] = useState<{lat: number, lng: number}[] | undefined>();

  // useEffect(() => {
  //   const properties = {
  //     "@odata.context": "$metadata#Property",
  //     "value": [
  //         {
  //             "ListingKeyNumeric": 10060,
  //             "AssociationFee": null,
  //             "RoomsTotal": 8,
  //             "Stories": 2,
  //             "BathroomsFull": 1,
  //             "BathroomsHalf": null,
  //             "BathroomsThreeQuarter": null,
  //             "BathroomsPartial": null,
  //             "BathroomsTotalInteger": 1,
  //             "BedroomsTotal": 3,
  //             "CarportSpaces": null,
  //             "CoveredSpaces": 2.0,
  //             "CoListAgentKeyNumeric": null,
  //             "CoListOfficeKeyNumeric": null,
  //             "CumulativeDaysOnMarket": null,
  //             "DaysOnMarket": 0,
  //             "FireplacesTotal": 1,
  //             "GarageSpaces": 2.0,
  //             "ListAgentKeyNumeric": 1963,
  //             "ListOfficeKeyNumeric": 50862,
  //             "ListPrice": 193000.0,
  //             "LeaseAmount": null,
  //             "LivingArea": 2025.0,
  //             "BuildingAreaTotal": 2025.0,
  //             "LotSizeAcres": 0.18,
  //             "LotSizeSquareFeet": 7840.8,
  //             "NumberOfBuildings": null,
  //             "NumberOfUnitsLeased": null,
  //             "NumberOfUnitsTotal": null,
  //             "LotSizeArea": 0.18,
  //             "MainLevelBedrooms": 3,
  //             "OriginalListPrice": 193000.0,
  //             "ParkingTotal": 2.0,
  //             "OpenParkingSpaces": null,
  //             "PhotosCount": 0,
  //             "StreetNumberNumeric": 2917,
  //             "TaxAnnualAmount": 1050.0,
  //             "YearBuilt": 1961,
  //             "YearBuiltEffective": null,
  //             "MobileLength": 0,
  //             "MobileWidth": 0,
  //             "BathroomsOneQuarter": null,
  //             "CapRate": null,
  //             "NumberOfPads": null,
  //             "StoriesTotal": null,
  //             "YearEstablished": null,
  //             "BuyerAgencyCompensation": "3",
  //             "CoListAgentFirstName": null,
  //             "CoListAgentFullName": "",
  //             "CoListAgentKey": null,
  //             "CoListAgentLastName": null,
  //             "CoListAgentMiddleName": null,
  //             "CoListAgentMlsId": "0",
  //             "CoListAgentStateLicense": null,
  //             "CoListOfficeKey": null,
  //             "CoListOfficeMlsId": null,
  //             "CoListOfficeName": null,
  //             "CopyrightNotice": "Copyright &#169; UtahRealEstate.com. All Rights Reserved.",
  //             "CrossStreet": "3600",
  //             "Exclusions": null,
  //             "FrontageLength": "0.0",
  //             "Inclusions": null,
  //             "ListAgentFirstName": "Jeffrey",
  //             "ListAgentFullName": "Jeffrey A White",
  //             "ListAgentKey": "1963",
  //             "ListAgentLastName": "White",
  //             "ListAgentMiddleName": "A",
  //             "ListAgentMlsId": "1963",
  //             "ListOfficeKey": "50862",
  //             "ListOfficeMlsId": "50862",
  //             "ListOfficeName": "Makris - White Real Estate",
  //             "ListingId": "10060",
  //             "ListingKey": "10060",
  //             "OriginatingSystemID": "M00000628",
  //             "OriginatingSystemKey": "1c5f133be8ee0a0e3b8637908f7a2767",
  //             "OriginatingSystemName": "UtahRealEstate.com",
  //             "OtherParking": null,
  //             "ParcelNumber": "16-25-153-002",
  //             "PostalCode": "84109",
  //             "PublicRemarks": "Estate sale home is being sold in \"as is\" condition great views quiet and peaceful neighborhood backs onto forest service ground",
  //             "RVParkingDimensions": null,
  //             "SourceSystemID": "M00000628",
  //             "SourceSystemKey": "M00000628",
  //             "SourceSystemName": "UtahRealEstate.com",
  //             "StreetName": "CASCADE",
  //             "StreetNumber": "2917",
  //             "SubdivisionName": "park terrace",
  //             "UnitNumber": "",
  //             "UnparsedAddress": "2917 S CASCADE WAY E",
  //             "VirtualTourURLUnbranded": null,
  //             "Zoning": null,
  //             "ZoningDescription": "res",
  //             "LotSizeDimensions": "0.0x0.0x0.0",
  //             "Topography": "Fenced: Part, Sprinkler: Auto-Full, Terrain: Hilly, View: Mountain, View: Valley",
  //             "BuilderName": null,
  //             "DOH1": null,
  //             "DOH2": null,
  //             "DOH3": null,
  //             "License1": null,
  //             "License2": null,
  //             "License3": null,
  //             "Make": null,
  //             "Model": null,
  //             "ParkName": null,
  //             "PostalCodePlus4": null,
  //             "SerialU": null,
  //             "SerialX": null,
  //             "SerialXX": null,
  //             "StreetAdditionalInfo": null,
  //             "StreetSuffixModifier": null,
  //             "WaterBodyName": null,
  //             "AssociationYN": false,
  //             "AttachedGarageYN": false,
  //             "CarportYN": false,
  //             "CoolingYN": true,
  //             "DualVariableCompensationYN": false,
  //             "FireplaceYN": true,
  //             "GarageYN": true,
  //             "HeatingYN": true,
  //             "HorseYN": false,
  //             "InternetAddressDisplayYN": true,
  //             "SearchableYN": true,
  //             "InternetEntireListingDisplayYN": true,
  //             "OpenParkingYN": false,
  //             "PoolPrivateYN": false,
  //             "SeniorCommunityYN": false,
  //             "SpaYN": false,
  //             "ViewYN": true,
  //             "NewConstructionYN": false,
  //             "InternetAutomatedValuationDisplayYN": true,
  //             "InternetConsumerCommentYN": true,
  //             "LeaseConsideredYN": false,
  //             "PropertyAttachedYN": false,
  //             "WaterfrontYN": false,
  //             "CloseDate": "1998-05-22",
  //             "ContingentDate": null,
  //             "ContractStatusChangeDate": "1998-05-22",
  //             "ListingContractDate": "1998-06-01",
  //             "OnMarketDate": "1998-06-01",
  //             "PurchaseContractDate": null,
  //             "ModificationTimestamp": "2023-06-21T19:10:59Z",
  //             "OriginalEntryTimestamp": "1998-06-01T18:13:00Z",
  //             "PhotosChangeTimestamp": null,
  //             "PriceChangeTimestamp": null,
  //             "StatusChangeTimestamp": "1998-05-22T06:00:00Z",
  //             "AssociationFeeFrequency": "",
  //             "City": "Aberdeen",
  //             "Country": "US",
  //             "CountyOrParish": "Salt Lake",
  //             "DirectionFaces": "",
  //             "ElementarySchool": "Eastwood",
  //             "ElementarySchoolDistrict": "Granite",
  //             "HighSchool": "Skyline",
  //             "HighSchoolDistrict": "Granite",
  //             "ListingService": "",
  //             "LivingAreaUnits": "Square Feet",
  //             "LotSizeUnits": "Acres",
  //             "MLSAreaMajor": "Holladay; Millcreek",
  //             "MiddleOrJuniorSchool": "Wasatch",
  //             "MiddleOrJuniorSchoolDistrict": "Granite",
  //             "MlsStatus": "Sold",
  //             "PostalCity": "Aberdeen",
  //             "PropertySubType": "Single Family Residence",
  //             "PropertyType": "Residential",
  //             "StandardStatus": "Closed",
  //             "StateOrProvince": "UT",
  //             "StreetDirPrefix": "S",
  //             "StreetDirSuffix": "E",
  //             "StreetSuffix": "",
  //             "LivingAreaSource": "",
  //             "YearBuiltSource": "",
  //             "AccessibilityFeatures": "",
  //             "Appliances": "",
  //             "ArchitecturalStyle": "Other/See Remarks",
  //             "AssociationAmenities": "",
  //             "AssociationFeeIncludes": "",
  //             "Basement": "Partial",
  //             "ConstructionMaterials": "Clapboard/Masonite,Stone",
  //             "Cooling": "Evaporative Cooling",
  //             "DoorFeatures": "",
  //             "ExteriorFeatures": "",
  //             "Flooring": "Hardwood",
  //             "GreenBuildingVerificationType": "",
  //             "Heating": "Gas: Central",
  //             "InteriorFeatures": "Bath: Master,Disposal,Range/Oven: Free Stdng.",
  //             "LaundryFeatures": "",
  //             "ListingTerms": "Conventional",
  //             "LotFeatures": "Fenced: Part,Sprinkler: Auto-Full,Terrain: Hilly,View: Mountain,View: Valley",
  //             "OtherEquipment": "",
  //             "ParkingFeatures": "",
  //             "PatioAndPorchFeatures": "",
  //             "PoolFeatures": "",
  //             "PropertyCondition": "Blt./Standing",
  //             "Roof": "Rolled-Silver",
  //             "Sewer": "Sewer: Connected,Sewer: Public",
  //             "Utilities": "Sewer Connected,Sewer: Public",
  //             "Vegetation": "Landscaping: Full",
  //             "View": "Mountain(s),Valley",
  //             "WaterSource": "Culinary",
  //             "WindowFeatures": "Full",
  //             "CurrentUse": "Single Family",
  //             "Fencing": "",
  //             "FireplaceFeatures": "",
  //             "GreenEnergyGeneration": "",
  //             "BodyType": "",
  //             "BuildingFeatures": "",
  //             "BusinessType": "",
  //             "CommonWalls": "",
  //             "CommunityFeatures": "",
  //             "Electric": "",
  //             "FoundationDetails": "",
  //             "GreenEnergyEfficient": "",
  //             "GreenIndoorAirQuality": "",
  //             "GreenLocation": "",
  //             "GreenSustainability": "",
  //             "GreenWaterConservation": "",
  //             "Levels": "",
  //             "OtherStructures": "",
  //             "PossibleUse": "",
  //             "RentIncludes": "",
  //             "RoadFrontageType": "",
  //             "RoadSurfaceType": "",
  //             "RoomType": "",
  //             "Skirt": "",
  //             "SpaFeatures": "",
  //             "SpecialListingConditions": "",
  //             "StructureType": "",
  //             "UnitTypeType": "",
  //             "WaterfrontFeatures": "",
  //             "GeoLocation": null,
  //             "BasementFinished": 80,
  //             "ConstStatus": "Blt./Standing",
  //             "PowerProductionSolarYearInstall": null,
  //             "SolarFinanceCompany": null,
  //             "SolarLeasingCompany": null,
  //             "SolarOwnership": null,
  //             "PowerProductionType": "",
  //             "LevelData": "levb_bathfull:0,levb_bathhalf:0,levb_bathtq:0,levb_bed:0,levb_den:0,levb_dining_f:0,levb_dining_s:0,levb_famroom:1,levb_fireplace:0,levb_formalliving:0,levb_kitchen_b:0,levb_kitchen_k:0,levb_laundry:0,levb_sqf:675,levb2_bathfull:0,levb2_bathhalf:0,levb2_bathtq:0,levb2_bed:0,levb2_den:0,levb2_dining_f:0,levb2_dining_s:0,levb2_famroom:0,levb2_fireplace:0,levb2_formalliving:0,levb2_kitchen_b:0,levb2_kitchen_k:0,levb2_laundry:0,levb2_sqf:0,levb3_bathfull:0,levb3_bathhalf:0,levb3_bathtq:0,levb3_bed:0,levb3_den:0,levb3_dining_f:0,levb3_dining_s:0,levb3_famroom:0,levb3_fireplace:0,levb3_formalliving:0,levb3_kitchen_b:0,levb3_kitchen_k:0,levb3_laundry:0,levb3_sqf:0,lev1_bathfull:1,lev1_bathhalf:0,lev1_bathtq:0,lev1_bed:3,lev1_den:0,lev1_dining_f:1,lev1_dining_s:0,lev1_famroom:0,lev1_fireplace:1,lev1_formalliving:0,lev1_kitchen_b:0,lev1_kitchen_k:0,lev1_laundry:1,lev1_sqf:1350,lev2_bathfull:0,lev2_bathhalf:0,lev2_bathtq:0,lev2_bed:0,lev2_den:0,lev2_dining_f:0,lev2_dining_s:0,lev2_famroom:0,lev2_fireplace:0,lev2_formalliving:0,lev2_kitchen_b:0,lev2_kitchen_k:0,lev2_laundry:0,lev2_sqf:0,lev3_bathfull:0,lev3_bathhalf:0,lev3_bathtq:0,lev3_bed:0,lev3_den:0,lev3_dining_f:0,lev3_dining_s:0,lev3_famroom:0,lev3_fireplace:0,lev3_formalliving:0,lev3_kitchen_b:0,lev3_kitchen_k:0,lev3_laundry:0,lev3_sqf:0,lev4_bathfull:0,lev4_bathhalf:0,lev4_bathtq:0,lev4_bed:0,lev4_den:0,lev4_dining_f:0,lev4_dining_s:0,lev4_famroom:0,lev4_fireplace:0,lev4_formalliving:0,lev4_kitchen_b:0,lev4_kitchen_k:0,lev4_laundry:0,lev4_sqf:0",
  //             "AboveGradeFinishedArea": 1350.0,
  //             "MasterBedroomLevel": "",
  //             "IrrigationWaterRightsAcres": null,
  //             "BuyerAgencyCompensationType": "",
  //             "ImageStatus": "All Public",
  //             "CompBacGrossNet": "Gross",
  //             "IdxContactInformation": "801-461-0000",
  //             "VowContactInformation": "801-461-0000",
  //             "ShortTermRentalYN": false,
  //             "AduYN": false
  //         },
  //         {
  //             "ListingKeyNumeric": 10063,
  //             "AssociationFee": null,
  //             "RoomsTotal": 12,
  //             "Stories": 2,
  //             "BathroomsFull": 2,
  //             "BathroomsHalf": null,
  //             "BathroomsThreeQuarter": 1,
  //             "BathroomsPartial": null,
  //             "BathroomsTotalInteger": 3,
  //             "BedroomsTotal": 6,
  //             "CarportSpaces": null,
  //             "CoveredSpaces": 2.0,
  //             "CoListAgentKeyNumeric": null,
  //             "CoListOfficeKeyNumeric": null,
  //             "CumulativeDaysOnMarket": null,
  //             "DaysOnMarket": 0,
  //             "FireplacesTotal": null,
  //             "GarageSpaces": 2.0,
  //             "ListAgentKeyNumeric": 36748,
  //             "ListOfficeKeyNumeric": 30371,
  //             "ListPrice": 159900.0,
  //             "LeaseAmount": null,
  //             "LivingArea": 2551.0,
  //             "BuildingAreaTotal": 2551.0,
  //             "LotSizeAcres": 0.29,
  //             "LotSizeSquareFeet": 12632.4,
  //             "NumberOfBuildings": null,
  //             "NumberOfUnitsLeased": null,
  //             "NumberOfUnitsTotal": null,
  //             "LotSizeArea": 0.29,
  //             "MainLevelBedrooms": 3,
  //             "OriginalListPrice": 164900.0,
  //             "ParkingTotal": 2.0,
  //             "OpenParkingSpaces": null,
  //             "PhotosCount": 0,
  //             "StreetNumberNumeric": 665,
  //             "TaxAnnualAmount": 766.0,
  //             "YearBuilt": 1986,
  //             "YearBuiltEffective": null,
  //             "MobileLength": 0,
  //             "MobileWidth": 0,
  //             "BathroomsOneQuarter": null,
  //             "CapRate": null,
  //             "NumberOfPads": null,
  //             "StoriesTotal": null,
  //             "YearEstablished": null,
  //             "BuyerAgencyCompensation": "",
  //             "CoListAgentFirstName": null,
  //             "CoListAgentFullName": "",
  //             "CoListAgentKey": null,
  //             "CoListAgentLastName": null,
  //             "CoListAgentMiddleName": null,
  //             "CoListAgentMlsId": "0",
  //             "CoListAgentStateLicense": null,
  //             "CoListOfficeKey": null,
  //             "CoListOfficeMlsId": null,
  //             "CoListOfficeName": null,
  //             "CopyrightNotice": "Copyright &#169; UtahRealEstate.com. All Rights Reserved.",
  //             "CrossStreet": null,
  //             "Exclusions": null,
  //             "FrontageLength": "0.0",
  //             "Inclusions": "Basketball Standard, Wood Stove",
  //             "ListAgentFirstName": "R. Scott",
  //             "ListAgentFullName": "R. Scott Stone",
  //             "ListAgentKey": "36748",
  //             "ListAgentLastName": "Stone",
  //             "ListAgentMiddleName": "",
  //             "ListAgentMlsId": "36748",
  //             "ListOfficeKey": "30371",
  //             "ListOfficeMlsId": "30371",
  //             "ListOfficeName": "Stone Associates Inc",
  //             "ListingId": "10063",
  //             "ListingKey": "10063",
  //             "OriginatingSystemID": "M00000628",
  //             "OriginatingSystemKey": "fadd8add1cb44110693c492d590e6c4c",
  //             "OriginatingSystemName": "UtahRealEstate.com",
  //             "OtherParking": null,
  //             "ParcelNumber": "53-062-0002",
  //             "PostalCode": "84097",
  //             "PublicRemarks": "New carpet and 12 tile entry/kitchen/laundry. Quiet cul-de-sac. Huge back yard w/ BB court/patio/playground. FRPLC, jetted tub, high efficiency furnace. Appraised @ $174,650! Must see! Price is firm.",
  //             "RVParkingDimensions": null,
  //             "SourceSystemID": "M00000628",
  //             "SourceSystemKey": "M00000628",
  //             "SourceSystemName": "UtahRealEstate.com",
  //             "StreetName": "450",
  //             "StreetNumber": "665",
  //             "SubdivisionName": "",
  //             "UnitNumber": "",
  //             "UnparsedAddress": "665 N 450 E",
  //             "VirtualTourURLUnbranded": null,
  //             "Zoning": null,
  //             "ZoningDescription": "",
  //             "LotSizeDimensions": "0.0x0.0x0.0",
  //             "Topography": "Cul-de-Sac, View: Mountain",
  //             "BuilderName": null,
  //             "DOH1": null,
  //             "DOH2": null,
  //             "DOH3": null,
  //             "License1": null,
  //             "License2": null,
  //             "License3": null,
  //             "Make": null,
  //             "Model": null,
  //             "ParkName": null,
  //             "PostalCodePlus4": null,
  //             "SerialU": null,
  //             "SerialX": null,
  //             "SerialXX": null,
  //             "StreetAdditionalInfo": null,
  //             "StreetSuffixModifier": null,
  //             "WaterBodyName": null,
  //             "AssociationYN": false,
  //             "AttachedGarageYN": true,
  //             "CarportYN": false,
  //             "CoolingYN": true,
  //             "DualVariableCompensationYN": true,
  //             "FireplaceYN": false,
  //             "GarageYN": true,
  //             "HeatingYN": true,
  //             "HorseYN": false,
  //             "InternetAddressDisplayYN": true,
  //             "SearchableYN": true,
  //             "InternetEntireListingDisplayYN": true,
  //             "OpenParkingYN": false,
  //             "PoolPrivateYN": false,
  //             "SeniorCommunityYN": false,
  //             "SpaYN": false,
  //             "ViewYN": true,
  //             "NewConstructionYN": false,
  //             "InternetAutomatedValuationDisplayYN": true,
  //             "InternetConsumerCommentYN": true,
  //             "LeaseConsideredYN": false,
  //             "PropertyAttachedYN": false,
  //             "WaterfrontYN": false,
  //             "CloseDate": "1998-10-29",
  //             "ContingentDate": null,
  //             "ContractStatusChangeDate": "1998-06-01",
  //             "ListingContractDate": "1998-06-01",
  //             "OnMarketDate": "1998-06-01",
  //             "PurchaseContractDate": "1998-09-07",
  //             "ModificationTimestamp": "2024-02-29T18:20:01Z",
  //             "OriginalEntryTimestamp": "1998-06-01T18:13:00Z",
  //             "PhotosChangeTimestamp": null,
  //             "PriceChangeTimestamp": "1998-08-31T17:51:00Z",
  //             "StatusChangeTimestamp": "1998-06-01T06:00:00Z",
  //             "AssociationFeeFrequency": "",
  //             "City": "Orem",
  //             "Country": "US",
  //             "CountyOrParish": "Utah",
  //             "DirectionFaces": "",
  //             "ElementarySchool": "None/Other",
  //             "ElementarySchoolDistrict": "",
  //             "HighSchool": "None/Other",
  //             "HighSchoolDistrict": "",
  //             "ListingService": "",
  //             "LivingAreaUnits": "Square Feet",
  //             "LotSizeUnits": "Acres",
  //             "MLSAreaMajor": "Pl Grove; Lindon; Orem",
  //             "MiddleOrJuniorSchool": "None/Other",
  //             "MiddleOrJuniorSchoolDistrict": "",
  //             "MlsStatus": "Sold",
  //             "PostalCity": "Orem",
  //             "PropertySubType": "Single Family Residence",
  //             "PropertyType": "Residential",
  //             "StandardStatus": "Closed",
  //             "StateOrProvince": "UT",
  //             "StreetDirPrefix": "N",
  //             "StreetDirSuffix": "E",
  //             "StreetSuffix": "",
  //             "LivingAreaSource": "",
  //             "YearBuiltSource": "",
  //             "AccessibilityFeatures": "",
  //             "Appliances": "",
  //             "ArchitecturalStyle": "Rambler/Ranch",
  //             "AssociationAmenities": "",
  //             "AssociationFeeIncludes": "",
  //             "Basement": "Full",
  //             "ConstructionMaterials": "Aluminum,Brick",
  //             "Cooling": "Evaporative Cooling",
  //             "DoorFeatures": "",
  //             "ExteriorFeatures": "",
  //             "Flooring": "Carpet,Tile",
  //             "GreenBuildingVerificationType": "",
  //             "Heating": "Gas: Central",
  //             "InteriorFeatures": "Disposal,Jetted Tub,Range: Gas",
  //             "LaundryFeatures": "",
  //             "ListingTerms": "Conventional",
  //             "LotFeatures": "Cul-De-Sac,View: Mountain",
  //             "OtherEquipment": "Basketball Standard,Wood Stove",
  //             "ParkingFeatures": "",
  //             "PatioAndPorchFeatures": "",
  //             "PoolFeatures": "",
  //             "PropertyCondition": "Blt./Standing",
  //             "Roof": "Asphalt",
  //             "Sewer": "Sewer: Connected",
  //             "Utilities": "Sewer Connected",
  //             "Vegetation": "Landscaping: Full",
  //             "View": "Mountain(s)",
  //             "WaterSource": "Culinary",
  //             "WindowFeatures": "Full",
  //             "CurrentUse": "Single Family",
  //             "Fencing": "",
  //             "FireplaceFeatures": "",
  //             "GreenEnergyGeneration": "",
  //             "BodyType": "",
  //             "BuildingFeatures": "",
  //             "BusinessType": "",
  //             "CommonWalls": "",
  //             "CommunityFeatures": "",
  //             "Electric": "",
  //             "FoundationDetails": "",
  //             "GreenEnergyEfficient": "",
  //             "GreenIndoorAirQuality": "",
  //             "GreenLocation": "",
  //             "GreenSustainability": "",
  //             "GreenWaterConservation": "",
  //             "Levels": "",
  //             "OtherStructures": "",
  //             "PossibleUse": "",
  //             "RentIncludes": "",
  //             "RoadFrontageType": "",
  //             "RoadSurfaceType": "",
  //             "RoomType": "",
  //             "Skirt": "",
  //             "SpaFeatures": "",
  //             "SpecialListingConditions": "",
  //             "StructureType": "",
  //             "UnitTypeType": "",
  //             "WaterfrontFeatures": "",
  //             "GeoLocation": null,
  //             "BasementFinished": 100,
  //             "ConstStatus": "Blt./Standing",
  //             "PowerProductionSolarYearInstall": null,
  //             "SolarFinanceCompany": null,
  //             "SolarLeasingCompany": null,
  //             "SolarOwnership": null,
  //             "PowerProductionType": "",
  //             "LevelData": "levb_bathfull:1,levb_bathhalf:0,levb_bathtq:0,levb_bed:3,levb_den:0,levb_dining_f:0,levb_dining_s:0,levb_famroom:1,levb_fireplace:0,levb_formalliving:0,levb_kitchen_b:0,levb_kitchen_k:0,levb_laundry:0,levb_sqf:1245,levb2_bathfull:0,levb2_bathhalf:0,levb2_bathtq:0,levb2_bed:0,levb2_den:0,levb2_dining_f:0,levb2_dining_s:0,levb2_famroom:0,levb2_fireplace:0,levb2_formalliving:0,levb2_kitchen_b:0,levb2_kitchen_k:0,levb2_laundry:0,levb2_sqf:0,levb3_bathfull:0,levb3_bathhalf:0,levb3_bathtq:0,levb3_bed:0,levb3_den:0,levb3_dining_f:0,levb3_dining_s:0,levb3_famroom:0,levb3_fireplace:0,levb3_formalliving:0,levb3_kitchen_b:0,levb3_kitchen_k:0,levb3_laundry:0,levb3_sqf:0,lev1_bathfull:1,lev1_bathhalf:0,lev1_bathtq:1,lev1_bed:3,lev1_den:0,lev1_dining_f:0,lev1_dining_s:1,lev1_famroom:0,lev1_fireplace:0,lev1_formalliving:0,lev1_kitchen_b:0,lev1_kitchen_k:0,lev1_laundry:1,lev1_sqf:1306,lev2_bathfull:0,lev2_bathhalf:0,lev2_bathtq:0,lev2_bed:0,lev2_den:0,lev2_dining_f:0,lev2_dining_s:0,lev2_famroom:0,lev2_fireplace:0,lev2_formalliving:0,lev2_kitchen_b:0,lev2_kitchen_k:0,lev2_laundry:0,lev2_sqf:0,lev3_bathfull:0,lev3_bathhalf:0,lev3_bathtq:0,lev3_bed:0,lev3_den:0,lev3_dining_f:0,lev3_dining_s:0,lev3_famroom:0,lev3_fireplace:0,lev3_formalliving:0,lev3_kitchen_b:0,lev3_kitchen_k:0,lev3_laundry:0,lev3_sqf:0,lev4_bathfull:0,lev4_bathhalf:0,lev4_bathtq:0,lev4_bed:0,lev4_den:0,lev4_dining_f:0,lev4_dining_s:0,lev4_famroom:0,lev4_fireplace:0,lev4_formalliving:0,lev4_kitchen_b:0,lev4_kitchen_k:0,lev4_laundry:0,lev4_sqf:0",
  //             "AboveGradeFinishedArea": 1306.0,
  //             "MasterBedroomLevel": "",
  //             "IrrigationWaterRightsAcres": null,
  //             "BuyerAgencyCompensationType": "",
  //             "ImageStatus": "All Public",
  //             "CompBacGrossNet": "Gross",
  //             "IdxContactInformation": "801-373-7653",
  //             "VowContactInformation": "801-373-7653",
  //             "ShortTermRentalYN": false,
  //             "AduYN": false
  //         },
  //         {
  //             "ListingKeyNumeric": 10073,
  //             "AssociationFee": null,
  //             "RoomsTotal": 13,
  //             "Stories": 2,
  //             "BathroomsFull": 2,
  //             "BathroomsHalf": null,
  //             "BathroomsThreeQuarter": 1,
  //             "BathroomsPartial": null,
  //             "BathroomsTotalInteger": 3,
  //             "BedroomsTotal": 4,
  //             "CarportSpaces": 1.0,
  //             "CoveredSpaces": 3.0,
  //             "CoListAgentKeyNumeric": null,
  //             "CoListOfficeKeyNumeric": null,
  //             "CumulativeDaysOnMarket": null,
  //             "DaysOnMarket": 0,
  //             "FireplacesTotal": 1,
  //             "GarageSpaces": 2.0,
  //             "ListAgentKeyNumeric": 47724,
  //             "ListOfficeKeyNumeric": 33300,
  //             "ListPrice": 169900.0,
  //             "LeaseAmount": null,
  //             "LivingArea": 2304.0,
  //             "BuildingAreaTotal": 2304.0,
  //             "LotSizeAcres": 0.24,
  //             "LotSizeSquareFeet": 10454.4,
  //             "NumberOfBuildings": null,
  //             "NumberOfUnitsLeased": null,
  //             "NumberOfUnitsTotal": null,
  //             "LotSizeArea": 0.24,
  //             "MainLevelBedrooms": 2,
  //             "OriginalListPrice": 179900.0,
  //             "ParkingTotal": 3.0,
  //             "OpenParkingSpaces": null,
  //             "PhotosCount": 0,
  //             "StreetNumberNumeric": 2941,
  //             "TaxAnnualAmount": 1200.0,
  //             "YearBuilt": 1983,
  //             "YearBuiltEffective": null,
  //             "MobileLength": 0,
  //             "MobileWidth": 0,
  //             "BathroomsOneQuarter": null,
  //             "CapRate": null,
  //             "NumberOfPads": null,
  //             "StoriesTotal": null,
  //             "YearEstablished": null,
  //             "BuyerAgencyCompensation": "3",
  //             "CoListAgentFirstName": null,
  //             "CoListAgentFullName": "",
  //             "CoListAgentKey": null,
  //             "CoListAgentLastName": null,
  //             "CoListAgentMiddleName": null,
  //             "CoListAgentMlsId": "0",
  //             "CoListAgentStateLicense": null,
  //             "CoListOfficeKey": null,
  //             "CoListOfficeMlsId": null,
  //             "CoListOfficeName": null,
  //             "CopyrightNotice": "Copyright &#169; UtahRealEstate.com. All Rights Reserved.",
  //             "CrossStreet": "7725",
  //             "Exclusions": null,
  //             "FrontageLength": "0.0",
  //             "Inclusions": "Hot Tub, Humidifier, Range, Range Hood, Refrigerator, Storage Shed(s)",
  //             "ListAgentFirstName": "Troy",
  //             "ListAgentFullName": "Troy McDougal",
  //             "ListAgentKey": "47724",
  //             "ListAgentLastName": "McDougal",
  //             "ListAgentMiddleName": "",
  //             "ListAgentMlsId": "47724",
  //             "ListOfficeKey": "33300",
  //             "ListOfficeMlsId": "33300",
  //             "ListOfficeName": "All West Inc.",
  //             "ListingId": "10073",
  //             "ListingKey": "10073",
  //             "OriginatingSystemID": "M00000628",
  //             "OriginatingSystemKey": "176cd351fe8673043ad0936a4f9a5132",
  //             "OriginatingSystemName": "UtahRealEstate.com",
  //             "OtherParking": null,
  //             "ParcelNumber": "22-26-378-027",
  //             "PostalCode": "84121",
  //             "PublicRemarks": "",
  //             "RVParkingDimensions": null,
  //             "SourceSystemID": "M00000628",
  //             "SourceSystemKey": "M00000628",
  //             "SourceSystemName": "UtahRealEstate.com",
  //             "StreetName": "Oakview Circle",
  //             "StreetNumber": "2941",
  //             "SubdivisionName": "",
  //             "UnitNumber": "",
  //             "UnparsedAddress": "2941 E OAKVIEW CIRCLE 7725 S",
  //             "VirtualTourURLUnbranded": null,
  //             "Zoning": null,
  //             "ZoningDescription": "",
  //             "LotSizeDimensions": "0.0x0.0x0.0",
  //             "Topography": "Cul-de-Sac, Fenced: Full, Secluded Yard, Sidewalks, Sprinkler: Auto-Full, Terrain: Grad Slope, View: Mountain, View: Valley",
  //             "BuilderName": null,
  //             "DOH1": null,
  //             "DOH2": null,
  //             "DOH3": null,
  //             "License1": null,
  //             "License2": null,
  //             "License3": null,
  //             "Make": null,
  //             "Model": null,
  //             "ParkName": null,
  //             "PostalCodePlus4": null,
  //             "SerialU": null,
  //             "SerialX": null,
  //             "SerialXX": null,
  //             "StreetAdditionalInfo": null,
  //             "StreetSuffixModifier": null,
  //             "WaterBodyName": null,
  //             "AssociationYN": false,
  //             "AttachedGarageYN": true,
  //             "CarportYN": true,
  //             "CoolingYN": true,
  //             "DualVariableCompensationYN": false,
  //             "FireplaceYN": true,
  //             "GarageYN": true,
  //             "HeatingYN": true,
  //             "HorseYN": false,
  //             "InternetAddressDisplayYN": true,
  //             "SearchableYN": true,
  //             "InternetEntireListingDisplayYN": true,
  //             "OpenParkingYN": false,
  //             "PoolPrivateYN": false,
  //             "SeniorCommunityYN": false,
  //             "SpaYN": false,
  //             "ViewYN": true,
  //             "NewConstructionYN": false,
  //             "InternetAutomatedValuationDisplayYN": true,
  //             "InternetConsumerCommentYN": true,
  //             "LeaseConsideredYN": false,
  //             "PropertyAttachedYN": false,
  //             "WaterfrontYN": false,
  //             "CloseDate": "1998-09-18",
  //             "ContingentDate": null,
  //             "ContractStatusChangeDate": "1998-06-01",
  //             "ListingContractDate": "1998-06-01",
  //             "OnMarketDate": "1998-06-01",
  //             "PurchaseContractDate": "1998-08-12",
  //             "ModificationTimestamp": "2024-03-21T16:06:47Z",
  //             "OriginalEntryTimestamp": "1998-06-01T18:55:00Z",
  //             "PhotosChangeTimestamp": null,
  //             "PriceChangeTimestamp": "1998-08-12T19:38:00Z",
  //             "StatusChangeTimestamp": "1998-06-01T06:00:00Z",
  //             "AssociationFeeFrequency": "",
  //             "City": "Holladay",
  //             "Country": "US",
  //             "CountyOrParish": "Salt Lake",
  //             "DirectionFaces": "",
  //             "ElementarySchool": "Butler",
  //             "ElementarySchoolDistrict": "Canyons",
  //             "HighSchool": "Brighton",
  //             "HighSchoolDistrict": "Canyons",
  //             "ListingService": "",
  //             "LivingAreaUnits": "Square Feet",
  //             "LotSizeUnits": "Acres",
  //             "MLSAreaMajor": "Sandy; Alta; Snowbd; Granite",
  //             "MiddleOrJuniorSchool": "Butler",
  //             "MiddleOrJuniorSchoolDistrict": "Canyons",
  //             "MlsStatus": "Sold",
  //             "PostalCity": "Holladay",
  //             "PropertySubType": "Single Family Residence",
  //             "PropertyType": "Residential",
  //             "StandardStatus": "Closed",
  //             "StateOrProvince": "UT",
  //             "StreetDirPrefix": "E",
  //             "StreetDirSuffix": "S",
  //             "StreetSuffix": "DR",
  //             "LivingAreaSource": "",
  //             "YearBuiltSource": "",
  //             "AccessibilityFeatures": "",
  //             "Appliances": "Range Hood,Refrigerator",
  //             "ArchitecturalStyle": "Split-Entry/Bi-Level",
  //             "AssociationAmenities": "",
  //             "AssociationFeeIncludes": "",
  //             "Basement": "Entrance,Full,Walk-Out Access",
  //             "ConstructionMaterials": "Aluminum",
  //             "Cooling": "Central Air,Evaporative Cooling",
  //             "DoorFeatures": "",
  //             "ExteriorFeatures": "Attic Fan,Entry (Foyer),Lighting,Patio: Covered,Porch: Screened,Sliding Glass Doors",
  //             "Flooring": "Carpet,Tile",
  //             "GreenBuildingVerificationType": "",
  //             "Heating": "Gas: Central",
  //             "InteriorFeatures": "Bath: Master,Disposal,Range/Oven: Free Stdng.,Vaulted Ceilings",
  //             "LaundryFeatures": "Electric Dryer Hookup",
  //             "ListingTerms": "Conventional,VA Loan",
  //             "LotFeatures": "Cul-De-Sac,Fenced: Full,Secluded,Sidewalks,Sprinkler: Auto-Full,Terrain: Grad Slope,View: Mountain,View: Valley",
  //             "OtherEquipment": "Hot Tub,Humidifier,Storage Shed(s)",
  //             "ParkingFeatures": "Rv Parking",
  //             "PatioAndPorchFeatures": "Covered,Screened",
  //             "PoolFeatures": "",
  //             "PropertyCondition": "Blt./Standing",
  //             "Roof": "Rubber,Stone",
  //             "Sewer": "Sewer: Connected,Sewer: Public",
  //             "Utilities": "Sewer Connected,Sewer: Public",
  //             "Vegetation": "Fruit Trees,Mature Trees",
  //             "View": "Mountain(s),Valley",
  //             "WaterSource": "Culinary",
  //             "WindowFeatures": "Blinds,Full",
  //             "CurrentUse": "Single Family",
  //             "Fencing": "",
  //             "FireplaceFeatures": "",
  //             "GreenEnergyGeneration": "",
  //             "BodyType": "",
  //             "BuildingFeatures": "",
  //             "BusinessType": "",
  //             "CommonWalls": "",
  //             "CommunityFeatures": "",
  //             "Electric": "",
  //             "FoundationDetails": "",
  //             "GreenEnergyEfficient": "",
  //             "GreenIndoorAirQuality": "",
  //             "GreenLocation": "",
  //             "GreenSustainability": "",
  //             "GreenWaterConservation": "",
  //             "Levels": "",
  //             "OtherStructures": "",
  //             "PossibleUse": "",
  //             "RentIncludes": "",
  //             "RoadFrontageType": "",
  //             "RoadSurfaceType": "",
  //             "RoomType": "",
  //             "Skirt": "",
  //             "SpaFeatures": "",
  //             "SpecialListingConditions": "",
  //             "StructureType": "",
  //             "UnitTypeType": "",
  //             "WaterfrontFeatures": "",
  //             "GeoLocation": null,
  //             "BasementFinished": 100,
  //             "ConstStatus": "Blt./Standing",
  //             "PowerProductionSolarYearInstall": null,
  //             "SolarFinanceCompany": null,
  //             "SolarLeasingCompany": null,
  //             "SolarOwnership": null,
  //             "PowerProductionType": "",
  //             "LevelData": "levb_bathfull:0,levb_bathhalf:0,levb_bathtq:0,levb_bed:0,levb_den:0,levb_dining_f:0,levb_dining_s:0,levb_famroom:0,levb_fireplace:0,levb_formalliving:0,levb_kitchen_b:0,levb_kitchen_k:0,levb_laundry:0,levb_sqf:0,levb2_bathfull:0,levb2_bathhalf:0,levb2_bathtq:0,levb2_bed:0,levb2_den:0,levb2_dining_f:0,levb2_dining_s:0,levb2_famroom:0,levb2_fireplace:0,levb2_formalliving:0,levb2_kitchen_b:0,levb2_kitchen_k:0,levb2_laundry:0,levb2_sqf:0,levb3_bathfull:0,levb3_bathhalf:0,levb3_bathtq:0,levb3_bed:0,levb3_den:0,levb3_dining_f:0,levb3_dining_s:0,levb3_famroom:0,levb3_fireplace:0,levb3_formalliving:0,levb3_kitchen_b:0,levb3_kitchen_k:0,levb3_laundry:0,levb3_sqf:0,lev1_bathfull:0,lev1_bathhalf:0,lev1_bathtq:1,lev1_bed:2,lev1_den:0,lev1_dining_f:0,lev1_dining_s:0,lev1_famroom:1,lev1_fireplace:1,lev1_formalliving:0,lev1_kitchen_b:0,lev1_kitchen_k:0,lev1_laundry:1,lev1_sqf:1062,lev2_bathfull:2,lev2_bathhalf:0,lev2_bathtq:0,lev2_bed:2,lev2_den:0,lev2_dining_f:0,lev2_dining_s:1,lev2_famroom:1,lev2_fireplace:0,lev2_formalliving:0,lev2_kitchen_b:1,lev2_kitchen_k:0,lev2_laundry:0,lev2_sqf:1242,lev3_bathfull:0,lev3_bathhalf:0,lev3_bathtq:0,lev3_bed:0,lev3_den:0,lev3_dining_f:0,lev3_dining_s:0,lev3_famroom:0,lev3_fireplace:0,lev3_formalliving:0,lev3_kitchen_b:0,lev3_kitchen_k:0,lev3_laundry:0,lev3_sqf:0,lev4_bathfull:0,lev4_bathhalf:0,lev4_bathtq:0,lev4_bed:0,lev4_den:0,lev4_dining_f:0,lev4_dining_s:0,lev4_famroom:0,lev4_fireplace:0,lev4_formalliving:0,lev4_kitchen_b:0,lev4_kitchen_k:0,lev4_laundry:0,lev4_sqf:0",
  //             "AboveGradeFinishedArea": 2304.0,
  //             "MasterBedroomLevel": "",
  //             "IrrigationWaterRightsAcres": null,
  //             "BuyerAgencyCompensationType": "",
  //             "ImageStatus": "All Public",
  //             "CompBacGrossNet": "Gross",
  //             "IdxContactInformation": "801-808-2644",
  //             "VowContactInformation": "801-808-2644",
  //             "ShortTermRentalYN": false,
  //             "AduYN": false
  //         }
  //       ],
  //       "@odata.nextLink": "https://resoapi.utahrealestate.com/reso/odata/Property?$skip=200"
  //   }

  //   const propertyLocations = properties.value.map(property => {
  //     const locationData = {
  //       address: property.UnparsedAddress,
  //       city: property.City,
  //       state: property.StateOrProvince,
  //     }
  //     return locationData
  //   })

  //   const coordStrings = propertyLocations.map(location => {
  //     const address = location.address.split(' ').join('+');
  //     const city = location.city.split(' ').join('+');
  //     const state = location.state.split(' ').join('+');
  //     return {address: address, city: city, state: state}
  //   })

  //   const getPropertyCoordinates = async () => {
  //     try {
  //       const promises = coordStrings.map(async address => {
  //         const response = await fetch(`${mapsURL}=${address.address},${address.city},${address.state}&key=${apiKey}`);
  //         const data = await response.json();

  //         if (data.results && data.results.length > 0) {
  //           const coords = data.results[0].geometry.location;
  //           return coords;
  //         } else {
  //           throw new Error("No results found for address: " + address.address);
  //         }
  //       });

  //       const coordsArray = await Promise.all(promises);
  //       if (coordsArray.length) {
  //         setPropertyCoordinates(coordsArray);
  //       }
  //     } catch (error) {
  //       console.error(error);
  //     }
  //   }

  //   getPropertyCoordinates()
  // }, [])

  if (propertyCoordinates?.length && apiKey) {
    return (
      <div className='googlemap component'>
        <div id='map'>
          <APIProvider apiKey={apiKey}>
            <ControlledMap
              propertyCoordinates={propertyCoordinates}
              mapId={mapId}
            />
          </APIProvider>
        </div>
      </div>
    );
  } else return <p className='googlemap component'>Loading...</p>;
};

const ControlledMap = ({
  propertyCoordinates,
  mapId,
}: {
  propertyCoordinates: { lat: number; lng: number }[];
  mapId: string;
}) => {
  return (
    <Map
      defaultZoom={defaultZoom}
      defaultCenter={centerPosition}
      mapId={mapId}
      zoomControl
      scrollwheel
      disableDoubleClickZoom
    >
      {propertyCoordinates.map((coordinates, index) => (
        <CustomMarker
          key={index}
          coordinates={coordinates as { lat: number; lng: number }}
          index={index}
        />
      ))}
    </Map>
  );
};

const CustomMarker = ({
  coordinates,
  index,
}: {
  coordinates: { lat: number; lng: number };
  index: number;
}) => {
  const [open, setOpen] = useState(false);

  return (
    <>
      <AdvancedMarker position={coordinates} key={index}>
        <Pin />
      </AdvancedMarker>
      {open && (
        <InfoWindow position={coordinates} onCloseClick={() => setOpen(false)}>
          <p>Pin info</p>
        </InfoWindow>
      )}
    </>
  );
};

export default GoogleMap;
